# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

build-common: &common-build

  working_directory: ~/repo

  steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

    - run: npm install

    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    # run tests!
    - run: npm run ci

jobs:
  node8:
    docker:
      - image: circleci/node:8
    <<: *common-build

  node10:
    docker:
      - image: circleci/node:10
    <<: *common-build

  node12:
    docker:
      - image: circleci/node:12
    <<: *common-build

workflows:
  version: 2
  test_node_versions:
    jobs:
      - node8
      - node10
      - node12
    
